### ISSUE TITLE
Accept Filename or Filename (path) Paramater from JRiver MC

### ISSUE THREAD

**Issue by jmone1** [3ll3d00d/madmeasurer#13]
Hi, Loving madmeasurer!  It would be great however if I could use MC's "Right Click--> Sent to" feature to send the title to meadmeasurer for processing.  MC has a set of fields that can be used, such as:
- Filename (path) : eg "\\MAIN\Media\Discs\AQUAMAN\BDMV\"
- Filename : eg "\\MAIN\Media\Discs\AQUAMAN\BDMV\index.bluray;1"
...but either of these currently need to be trucated to "\\MAIN\Media\Discs\AQUAMAN" to work with madmeasurer.  
Thanks
Nathan

**Comment by 3ll3d00d** [comment]
so making BDMV an optional path element when using `-d0` would work?

**Comment by jmone1** [comment]
I guess so!  Easy enough for me to test.  Thanks for looking.

**Comment by 3ll3d00d** [comment]
I guess even easier would be to replace `index.bluray;1` with the actual filename

**Comment by jmone1** [comment]
Yup, replacing "bluray;1" with "bdmv" would work and would be a better idea as the same MC "Sent To" command would then also work with single files (like MKV) etc.  This is one oddity with MC, of not storing the actual filename but marking it as a group I guess (it is a similar thing with DVD folder rips).  I do the same "bluray;1" to "bdmv" in Swag of Tools.

**Comment by 3ll3d00d** [comment]
should turn up in a 1.0.3 release shortly

**Comment by jmone1** [comment]
:) thanks - will test and report back

**Comment by jmone1** [comment]
Hi, I got this following error:
`M:\Media\MadMeasure>M:\Media\MadMeasure\madmeasurer.exe -vvv --main-by-jriver --mad-measure-path "C:\Users\natha\AppData\Roaming\J River\Media Center 25\Plugins\madvr" -m  "\\MAIN\Media\Discs\GUARDIANS_OF_THE_GALAXY_1\BDMV\index.bluray;1"
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_win32comgenpy.py", line 47, in <module>
  File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\win32com\__init__.py", line 5, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
[6416] Failed to execute script pyi_rth_win32comgenpy`

**Comment by 3ll3d00d** [comment]
1.0.4 should work

**Comment by jmone1** [comment]
Yes it does!  Right Click --> Send to --> Madmeasurer makes it super easy after importing a rip into MC.  Thanks Nathan
