### ISSUE TITLE
Support for other main playlist selection algos

### ISSUE THREAD

**Issue by ManniGH** [3ll3d00d/madmeasurer#3]
Hi there,

Thanks again for the tool, it works great. I wasn't sure how to request a feature, so apologies if this is the wrong section to do so.

As discussed on AVS, it would be great if you could implement a few other algos to pick the main playlist, as current libbluray and use-lav ones do miss a few titles:

An MPC-BE algo would be great.

A jRiver algo would be welcome too, if possible.

Having the option to combine different algos in the same command line (for example --mpc-be --jriver) would be fantastic.

An option to measure all .mpls for all algos (--all-algos) might be useful for those who want to be on the safe side at the expense of speed.

Thanks again for your work!

**Comment by 3ll3d00d** [comment]
I was thinking of doing that sort of thing (`--all-algos`) and dumping the output to a CSV as I think the interesting bit will be where the different algos differ.

**Comment by 3ll3d00d** [comment]
new build added - https://github.com/3ll3d00d/madmeasurer/releases/tag/0.7.0 - which implements parts of this

there are about 10% of BDs in my library which have different main titles when comparing mpc-be to libbluray and a slightly smaller number are different when comparing a duration only sort vs mpc-be

It would be interesting to know whether you see a similar proportion

I'll have a look at some of the differences in more detail to see which one is correct (am assuming the ones that agree are correct, might not be true though)

**Comment by ManniGH** [comment]
Only found your replies after our discussion on the jRiver forum.
So in build 10 we have a jRiver option now, and I assume the --analyse-main-algos from build 8 is still active. Can we trigger separately the jriver option and an mpc-be option, or do we have to run the --analyse-main-algos to get them both covered?
