### ISSUE TITLE
Don't re-measure if incomplete file exists

### ISSUE THREAD

**Issue by ManniGH** [3ll3d00d/madmeasurer#4]
After a first scan, a BD Folder might lead to an incomplete file.

In that case, even if -f isn't used, the same playlist is remeasured every time the scan is run.

The only way to avoid it is to rename the incomplete file as if it was complete, but that's of course undesirable as it can cause issues with madVR during playback.

Thanks!

**Comment by 3ll3d00d** [comment]
what do you mean by an incomplete file exactly?

**Comment by ManniGH** [comment]
Sorry, I only saw your comments to my various requests now. I had asked to be told when replies were posted but that clearly doesn't work.

when madmeasureHDR.exe can't complete a measurements file for whatever reason, it creates a xxxxx.mpls.measurements.incomplete file instead of a xxxxx.mpls.measurements file. So you should test for the existence of such a file before running a measurement if xxxx.mpls.measurements doesn't exist. Otherwise the utility keeps measuring a file that can't be measured in an endless loop.

**Comment by 3ll3d00d** [comment]
fixed in https://github.com/3ll3d00d/madmeasurer/releases/tag/0.11.0

**Comment by ManniGH** [comment]
tested, works fine thanks. Really annoying that I don't get any notifications, no idea why!
