### ISSUE TITLE
MAD_MEASURE_HDR_PATH doesn't work

### ISSUE THREAD

**Issue by ManniGH** [3ll3d00d/madmeasurer#8]
If I specify the path for madmeasureHDR.exe using the --mad-measure-hdr parameter, all works fine.

If I try to set the MAD_MEASURE_HDR_PATH instead, it doesn't work. For some reason, the tools seems to add before the path specified in MAD_MEASURE_HDR_PATH the path where the tool itself is located.

For example, if I define:

set pathToMadMeasurer="D:\Em\Dropbox\Install\Media Centre Pack\MadVR Tools\madmeasurer.exe"
set MAD_MEASURE_HDR_PATH="C:\Users\MyMovies\AppData\Roaming\J River\Media Center 25\Plugins\madvr"

When I launch the command:
%pathToMadMeasurer% -d1 -vv -c --main-by-jriver-minute-resolution --no-main-by-libbluray --main-by-mpc-be --describe-bd -m N:\ --mad-measure-path "C:\Users\MyMovies\AppData\Roaming\J River\Media Center 25\Plugins\madvr"

everything is fine because I don't use the MAD_MEASURE_HDR_PATH variable.

But if I try the command:
%pathToMadMeasurer% -d1 -vv -c --main-by-jriver-minute-resolution --no-main-by-libbluray --main-by-mpc-be  --describe-bd -m O:\

the tool tries to launch the following command:

['D:\\Em\\Dropbox\\Install\\Media Centre Pack\\MadVR Tools\\"C:\\Users\\MyMovies\\Appdata\\Roaming\\J River\\Media Center 25\\Plugins\\madvr"\\madmeasureHDR.exe', 'O:\\Despicable_Me\\BDMV\\PLAYLIST\\01069.mpls']

adding the wrong path (path to the tool less the madmeasurer.exe) + correct path, instead of:

['C:\\Users\\MyMovies\\Appdata\\Roaming\\J River\\Media Center 25\\Plugins\\madvr"\\madmeasureHDR.exe', 'O:\\Despicable_Me\\BDMV\\PLAYLIST\\01069.mpls']

If I don't define MAD_MEASURE_HDR_PATH, it also tries to launch the wrong path, like this:

['D:\\Em\\Dropbox\\Install\\Media Centre Pack\\MadVR Tools\\madmeasureHDR.exe', 'O:\\Despicable_Me\\BDMV\\PLAYLIST\\01069.mpls']

I'm not sure why. Maybe it's because I launch the tool with %pathToMadMeasurer% and it confuses the two environment variables?

**Comment by 3ll3d00d** [comment]
I noticed this before and it confused me for a while, try this instead

`set MAD_MEASURE_HDR_PATH=C:\Users\MyMovies\AppData\Roaming\J River\Media Center 25\Plugins\madvr`

i.e. no double quotes around the path

it should work then

I'll add something to strip off quotes if they are on the env var as well though

**Comment by ManniGH** [comment]
but if I don't put the double quote the VAR will be "C:\Users\MyMovies\AppData\Roaming\J" as it will be truncated after the first space, no?

**Comment by ManniGH** [comment]
The issue isn't the double quotes by the way, it is that a wrong path is added in front of the path specified in the environment VAR. That same (wrong) path is used if no VAR is defined. Look at the example I provided, you will see what I mean.

**Comment by ManniGH** [comment]
Anyway, scratch the above, I tried the new build and it works fine :)

Thanks for the very quick fix
