### ISSUE TITLE
Maximum depth not working with  --measure-all-playlists

### ISSUE THREAD

**Issue by ManniGH** [3ll3d00d/madmeasurer#9]
I'm using --measure-all-playlists to measure my TV Series shares.

The structure is similar to my films, except that there is usually one more directory level due to the series, so I used -d3 instead of -d1 assuming that it would measured all series, whether they had a series subfolder or not.

The problem is that when specifying -d3, the tool will only measure at that level. It won't measure at d1, d2 or d0.

For examples, my series with a series x subfolder (Westworld\Series1\Disc1) are measured, but my series without a series x subfolder (Planet Earth II\Disc1 hence a depth of 2, not 3) are not measured.

I haven't tested if this unwanted behaviour also happens without using the  --measure-all-playlists parameter.

I might have misunderstood how it works, but the depth parameter is supposed to be a max depth from its description, not an exact depth.

An exact depth parameter might be useful too, but it should be two different parameters in that case, for example -dx for exact depth and -maxdx for max depth (as described currently).

Thanks!

**Comment by 3ll3d00d** [comment]
the wording is bad, it is an exact-depth search. I'll add both options though.

**Comment by ManniGH** [comment]
Thanks!

**Comment by ManniGH** [comment]
Tested, works great, though I don't think you have documented --max-depth (or I missed it). I had to look up the source code to find it :)

**Comment by 3ll3d00d** [comment]
good point, have updated the readme
